# site settings
title: Peru Dayani
subtitle: 
email: perudayani@berkeley.edu
description: Engineer | Innovator | Teacher
baseurl:  '/perudayani/' # the subpath of your site, e.g. /blog
url: https://perudayani.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Berkeley
state: CA
zip_code: 
country: United States of America
phone: 510-710-5389

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
linkedin_url: https://www.linkedin.com/in/peru-dayani-09367314a/
github_url: https://github.com/PeruDayani
facebook_url:  https://www.facebook.com/peru.dayani
gitlab_url: 
googleplus_url: 
instagram_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
